### ISSUE TITLE
Fix Default Mat Button Height Issue

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-themes#103]
#### Describe the bug
Angular material default `mat-button` is not 36px height.

#### What is the expected behavior?
Default `mat-button` should be 36px high.

#### What are the steps to reproduce?
1. Run the showcase and observe the height of these buttons is pretty small, smaller than normally. 

#### Screenshots or links to minimum reproduction example
<img width="364" alt="Screen Shot 2022-03-28 at 1 57 18 PM" src="https://user-images.githubusercontent.com/6538289/160469521-70d2d07c-fdb8-446f-9c04-d5777fae1d3a.png">

#### Environment
Chrome, Mac
		
#### Anything else to add?
No

**Comment by JeanMeche** [comment]
Hi, 
I commented on the PR, on wether the fix was the right one.
