### ISSUE TITLE
Add dense input styles to the Angular theme

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-themes#124]
#### Describe the desired behavior
Add dense input styles to the Angular themes so we don't need an abundance of styles to achieve something similar to the Forms and Validation 'In a list" example. (This should be able to be done in a similar way that the chip styles are implemented)

https://stackblitz.com/github/pxblue/angular-design-patterns?file=src%2Fapp%2Fpages%2Fforms-and-validation%2Fin-a-list%2Fin-a-list.component.ts 

#### Describe the current behavior
Dense mode does not exist.

#### Is this request related to a current issue?
No

#### Additional Context

Transferred from JIRA; Requested by Green Motion
Julien Von Oetinger (jvonoetinger@greenmotion.ch) might have a working & encapsulated style that you can borrow.

**Comment by ektasawant** [comment]
Not planning to work on this issue unless some adopter team come up with this requirement.
