### ISSUE TITLE
Dropdown menu, hover text color shall be black

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-themes#18]
The `+91 (IN)` part should be black. React side is OK.
![](https://user-images.githubusercontent.com/37150565/132000810-9e34f1de-4509-4d14-97a9-b4e10d8dd8b1.png)

**Comment by jeffvg** [comment]
low priority for R21 Q3

**Comment by joebochill** [comment]
@huayunh what if it is active and hovered?

**Comment by huayunh** [comment]
I guess that can be a possible solution. So hover = background color change, and active = text color change. This can avoid the dilemma discussed in #45. 

Although from a designer's perspective, I would always suggest https://github.com/brightlayer-ui/angular-themes/pull/45#issuecomment-984750162 to avoid ambiguity.
