### ISSUE TITLE
Blue outlined version of toggle button group

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/angular-themes#19]
#### Describe the desired behavior
Add the option for using blue outlined version of the toggle button group

#### Describe the current behavior
Only the gray-outlined version is available

#### Is this request related to a current issue?
This is something that was brought up by the IPM team.

#### Additional Context

![image](https://user-images.githubusercontent.com/29152776/133451056-82217206-72ef-4ec8-8fc6-a3bc01168600.png)

**Comment by ektasawant** [comment]
In current angular material `mat-button-toggle-group`  implementation border is assigned to group not to each button.
<img width="323" alt="Screenshot 2022-01-13 at 11 46 25 AM" src="https://user-images.githubusercontent.com/10433274/149275959-2fb12988-7e88-4a01-a4d5-59481c015987.png">

As per our figma designs we need to change border color of each selected button, which needs to change current behaviour of `mat-button-toggle-group`. I have updated themes changes to highlight selected button with some border styling tweak in PR https://github.com/brightlayer-ui/angular-themes/pull/58. Not sure will it be a good solution to change border of selected button.

**Comment by emclaug2** [comment]
Fixed in #58
