### ISSUE TITLE
Stepper RTL Support

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-themes#2]
#### Describe the bug
Angular material stepper is struggling with RTL switches halfway through a workflow.  

#### What is the expected behavior?
Stepper 'edit icon' should be center aligned when switching in/out of RTL. 

#### What are the steps to reproduce?
1. Go to demo.
2. Click next step on stepper
3. Turn on RTL
4. Observe edit icon offset, 

#### Screenshots or links to minimum reproduction example
![vertical stepper](https://user-images.githubusercontent.com/6538289/109808730-7a0fec80-7bf5-11eb-8eee-524b44d80a7e.gif)

#### Environment

Chrome Windows		

#### Anything else to add?
This is an angular material issue.

**Comment by joebochill** [comment]
Looks like we need to follow up on this and get that bug logged on Angular material so we can close this.

**Comment by huayunh** [comment]
1. Spin your own project using Angular's CLI (not BLUI CLI), without any BLUI theme / component library. Test this over the latest Angular Material (ng13?)
2. Plug this in 
3. Test on both left to right and right to left
4. If the problem persists, log an issue on Angular Material's repo, link to that issue from here, and close this issue.

**Comment by emclaug2** [comment]
@andrupu We're going to kick this issue into the next milestone so there's no rush to complete this.

**Comment by emclaug2** [comment]
This issue is no longer happening in our showcase example running on angular 14.
