### ISSUE TITLE
Angular theme should look nicer for table headers

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-themes#36]
#### Describe the desired behavior

The table header row should look more like this. 
- Color: primary text
- font: subtitle-2, as [defined on doc-it](https://pxblue.github.io/style/typography#type-scale)

![column-order-1](https://user-images.githubusercontent.com/8997218/137418423-cd0e3ad3-83e0-47dc-9009-9025e62c5acb.png)

#### Describe the current behavior

![image](https://user-images.githubusercontent.com/8997218/137418334-878b5108-20b9-4cba-8845-16ddb6853259.png)

**Comment by huayunh** [comment]
2628

**Comment by emclaug2** [comment]
Fixed in #64
