### ISSUE TITLE
Table row height should be 52

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-themes#37]
#### Describe the desired behavior

52dp for table row height, like this:

<img width="600" alt="spec-size" src="https://user-images.githubusercontent.com/8997218/137419073-38b840a3-d91d-4c83-ba0f-51ca2432dcba.png">

#### Describe the current behavior

48dp by default.

The header row is at the correct size (56dp)

**Comment by huayunh** [comment]
2628

**Comment by huayunh** [comment]
Fixed in the PR above

**Comment by joebochill** [comment]
The min-height property doesn't actually have any effect on table layout elements. We need to use `height` instead (it has the same effect as you'd expect from min-height when used in a table component).

The showcase right now has rows at 48px instead of 52.
