### ISSUE TITLE
Chevron shift in accordion

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-themes#39]
## Describe the bug

The chevron would "jump" when the accordion is clicked on

![ezgif com-gif-maker](https://user-images.githubusercontent.com/8997218/137810570-fef89458-093c-42c3-922e-22cee5a1e7a4.gif)
(Slowed down 3x to show the transition)

## What is the expected behavior?

It should stay centered.

#### Environment
Mac Chrome
		
#### Anything else to add?
This is discovered in status list of Angular Design Patterns

**Comment by huayunh** [comment]
Oof, didn't type the "f"

**Comment by joebochill** [comment]
If this is an issue in the out of the box angular material accordion, let's log an issue there and close this.

**Comment by emclaug2** [comment]
This is probably a duplicate issue.

**Comment by bkarambe** [comment]
Closing this one, as this is already been addressed in https://github.com/brightlayer-ui/angular-themes/pull/55
