### ISSUE TITLE
Text Field Style Issues

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/angular-themes#48]
Ported from a comment on https://github.com/brightlayer-ui/themes/issues/124

Here is a list of things that need to be corrected:

# 1
Applies to: all form field styles
Text field height shall be 56px
![image](https://user-images.githubusercontent.com/8997218/121703227-9c40c280-caa0-11eb-9a77-4f453154a64f.png)

# 2
Applies to: all form field styles
trailing and leading icons shall be vertically centered
![image](https://user-images.githubusercontent.com/8997218/121703715-1a9d6480-caa1-11eb-829e-460be600bcd4.png)

# 3 
Applies to: legacy form field and standard form field
label text shall be vertically centered when the text field is inactive.
![image](https://user-images.githubusercontent.com/8997218/121704056-651ee100-caa1-11eb-8793-5af77224f527.png)
What it should look like:
![image](https://user-images.githubusercontent.com/8997218/121704265-95ff1600-caa1-11eb-901b-72e3ff6190e6.png)

# 4
Applies to: all form field styles
Hint text height shall be 20px. Right now it looks too distanced.
![image](https://user-images.githubusercontent.com/8997218/121729907-ff405280-cabc-11eb-80b2-b3f6349f13ea.png)

# 5
Applies to: fill and outline
Left padding shall be 16px
![image](https://user-images.githubusercontent.com/8997218/121705083-54bb3600-caa2-11eb-8e34-f85b25254992.png)

# 6 
Applies to: legacy form field and standard form field
This is kinda tricky to tweak... basically, in DSM, the box that contains the form label and input text should be vertically centered.

![image](https://user-images.githubusercontent.com/8997218/121728592-7d9bf500-cabb-11eb-88d5-ce6dd7d0fe93.png)

This orange box is 39px tall in DSM, which is a result of 17px from label text (purple box from below), and 22px from input text (green box)

![image](https://user-images.githubusercontent.com/8997218/121728928-e3887c80-cabb-11eb-836d-76200b4caefd.png)

Surprisingly, styles of the fill form field and outline form field look way better

# 7 
Browser autofill style kinda goofy in dark theme, but I don't know if this is something we shall control. The background color comes from the user agent style `input:-internal-autofill-selected`
![image](https://user-images.githubusercontent.com/8997218/121729711-c4d6b580-cabc-11eb-9142-5419fabbe571.png)

**Comment by huayunh** [comment]
Andrew you picked a tough one :P

**Comment by andrupu** [comment]
After talking with you in person, @huayunh, it sounds like this might be a bigger issue.  Maybe a team-wide collaboration to get more brains and knowledge-base on this.

**Comment by emclaug2** [comment]
I'm working to split this issue into much more digestible pieces, as it stands this issue is going to take a while to complete.

**Comment by emclaug2** [comment]
I moved the last issue (no. 7) in the list to a new issue #76.  There's a lot to review in #71.

**Comment by emclaug2** [comment]
Fixed in #71
