### ISSUE TITLE
Typography should align with documentation specifications

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/angular-themes#49]
#### Describe the desired behavior
Typography classes and directives should align with the Material standards.

#### Describe the current behavior
The default styles and class names do not align.

#### Additional Context

Update the theme so that all of the mat classes actually makes sense. The topography styles should match what is specified on the doc-it typography page.

We researched before and confirmed that none of the existing Ng Mat components will be affected... but may want to double check this.

- Ensure that all our existing blui components still stay the same
- Include a table somewhere in NG's theme readme 
- Update docit as described here: https://github.com/pxblue/doc-it/issues/369

**Comment by jeffvg** [comment]
we can extend the existing classes and not override them

**Comment by emclaug2** [comment]
Fixed in #91
