### ISSUE TITLE
Card header feels not center-aligned

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-themes#52]
https://pxblue-components.github.io/angular-dev/?path=/story/components-empty-state--within-a-card feels a bit off-centered to my eye (~2px off)

![image](https://user-images.githubusercontent.com/8997218/136558154-e86989ce-c9ea-47d1-8755-8ed908d94016.png)

**Comment by bkarambe** [comment]
PR raised https://github.com/brightlayer-ui/angular-themes/pull/51
