### ISSUE TITLE
Text Field Height Issue

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-themes#82]
#### Describe the bug
Text Field should not have the 3.5rem specific height; it needs to grow and shrink.

#### What is the expected behavior?
Text Field should not have the 3.5rem specific height.

#### What are the steps to reproduce?
1.  Add a text field to the showcase & observe.
2. https://material.angular.io/components/input/overview

#### Screenshots or links to minimum reproduction example
![Text Input](https://user-images.githubusercontent.com/6538289/152907391-678e5fbf-bb56-4dce-9a35-19248fbecbfb.gif)

#### Environment

Windows Chrome
		
#### Anything else to add?
This is not a difficult thing to fix; there was a new style rule added to our angular themes (unpublished) that manually sets the height of all input fields.  Update this style rule to not apply to Text Fields, only Input Fields.

**Comment by emclaug2** [comment]
I'm also adding this to the 6.4.0 milestone since this is a bug introduced by the current implementation of 6.4.0.

**Comment by huayunh** [comment]
@emclaug2 is this fixed now?

**Comment by emclaug2** [comment]
Yep, closing this issue as this is fixed.
