### ISSUE TITLE
Update stepper input styles with latest styles

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/angular-themes#90]
#### Describe the bug
The input fields in stepper example display labels chopped off

#### What is the expected behavior?
label to display while input field contains text
#### What are the steps to reproduce?
1. Go to...showcase demo
2. Click on...http://localhost:4200/material-components/navigation-components
3. stepper card and fill in input fields

#### Screenshots or links to minimum reproduction example
<img width="331" alt="image" src="https://user-images.githubusercontent.com/37150565/153951528-427f8381-1e6b-4c1b-be77-07ce53c53b0a.png">

**Comment by ektasawant** [comment]
Changes are merged.
