### ISSUE TITLE
`blui-inline` shall support suffix icons

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-themes#94]
#### Describe the desired behavior

I want to implement this with `blui-inline`

![image](https://user-images.githubusercontent.com/8997218/155604237-0341e74c-8bad-4c41-a7d9-812ad916fcfd.png)

#### Describe the current behavior

It will be broken with the `blui-inline` directive
![image](https://user-images.githubusercontent.com/8997218/155604390-7f7c44af-f11f-4eb1-afee-a2e8438e9cea.png)

The style should be similar to this, but reversed for suffixed icons

<img width="270" alt="image" src="https://user-images.githubusercontent.com/8997218/155604483-329eee09-0a96-498e-8c3d-4035cfbace16.png">

#### Additional Context
We were trying to introduce it to the CYME team and noticed this halfway through

**Comment by jeffvg** [comment]
This has been fixed
